//! Teal declarations (`.d.tl`) for the Lua modules, shipped with the crate.
//!
//! A Teal project (htl) type-checks `require("mlua_batteries.json")` against
//! a declaration file found on its `types/` path as
//! `types/mlua_batteries/json.d.tl`.  The files live in this crate under
//! `types/mlua_batteries/` and are embedded here, so a host can write them
//! out without depending on the crate's source layout:
//!
//! ```rust,no_run
//! // types/mlua_batteries/<module>.d.tl + types/mlua_batteries/init.d.tl
//! mlua_batteries::dts::write_to("types", mlua_batteries::PRELOAD_PREFIX).unwrap();
//! ```
//!
//! # The prefix is not baked in
//!
//! A `.d.tl` body never names its own module — only its path does.  So the
//! prefix is chosen at write time, to match whatever the host passed
//! [`preload_all`](crate::preload_all): a host that exposes the modules as
//! `std.*` writes `write_to("types", "std")` and gets `types/std/json.d.tl`.
//! The only file that mentions module names, the generated `init.d.tl`
//! (the namespace record behind `require("<prefix>")`), is rendered for
//! that prefix by [`init_source`].
//!
//! # Feature flags
//!
//! [`entries`] lists only the modules whose cargo feature is enabled, so a
//! host never writes a declaration for a module it did not build.  That is
//! why materialisation is a Rust call rather than a static copy of the
//! crate's `types/` directory.
//!
//! # Keeping declarations honest
//!
//! The files are written by hand.  A test in `tests/dts_drift.rs` builds
//! every module and checks that the record's field names equal the
//! module table's keys, in both directions, so a function added or renamed
//! in Rust fails the build until its declaration follows.

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

/// One shipped declaration: the module's short name (`"json"`) and the
/// `.d.tl` source.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Entry {
    /// Module name below the prefix: `require("<prefix>.<name>")`.
    pub name: &'static str,
    /// The declaration file, verbatim.
    pub source: &'static str,
}

/// The declarations for every enabled module, in the order
/// [`module_entries`](crate::module_entries) uses (plus `task`, which is
/// reachable through [`preload_all`](crate::preload_all) but not part of
/// the synchronous namespace).
pub fn entries() -> Vec<Entry> {
    let mut entries = Vec::new();

    macro_rules! entry {
        ($name:literal) => {{
            #[cfg(feature = $name)]
            entries.push(Entry {
                name: $name,
                source: include_str!(concat!("../types/mlua_batteries/", $name, ".d.tl")),
            });
        }};
    }

    entry!("json");

    entries
}

/// Source of the namespace declaration behind `require("<prefix>")`: a
/// record with one field per enabled module, each typed by that module's
/// own declaration.
pub fn init_source(prefix: &str) -> String {
    let record_name = prefix.rsplit('.').next().unwrap_or(prefix);
    let mut out = String::new();
    out.push_str("-- Generated by mlua_batteries::dts for prefix `");
    out.push_str(prefix);
    out.push_str("`: the namespace behind require(\"");
    out.push_str(prefix);
    out.push_str("\").\n");
    for e in entries() {
        out.push_str(&format!(
            "local type {alias} = require(\"{prefix}.{name}\")\n",
            alias = type_alias(e.name),
            name = e.name
        ));
    }
    out.push_str(&format!("\nlocal record {record_name}\n"));
    for e in entries() {
        out.push_str(&format!(
            "   {name}: {alias}\n",
            name = e.name,
            alias = type_alias(e.name)
        ));
    }
    out.push_str(&format!("end\n\nreturn {record_name}\n"));
    out
}

/// `json` → `Json`: a type alias that cannot collide with the field name.
fn type_alias(name: &str) -> String {
    let mut chars = name.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().chain(chars).collect(),
        None => String::new(),
    }
}

/// Write every enabled declaration plus the generated `init.d.tl` under
/// `dir/<prefix as path>/`, creating directories as needed, and return
/// the paths written.
///
/// `prefix` is the `require` prefix (`"mlua_batteries"`, `"std"`, or a
/// dotted one such as `"vendor.std"`, which becomes nested directories).
/// Existing files are overwritten: the declarations belong to the crate
/// version the host builds against, and a stale copy is exactly the drift
/// this is meant to remove.
pub fn write_to(dir: impl AsRef<Path>, prefix: &str) -> io::Result<Vec<PathBuf>> {
    let mut base = dir.as_ref().to_path_buf();
    for segment in prefix.split('.') {
        base.push(segment);
    }
    fs::create_dir_all(&base)?;

    let mut written = Vec::new();
    for e in entries() {
        let path = base.join(format!("{}.d.tl", e.name));
        fs::write(&path, e.source)?;
        written.push(path);
    }
    let init = base.join("init.d.tl");
    fs::write(&init, init_source(prefix))?;
    written.push(init);
    Ok(written)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn init_source_names_every_entry_under_the_prefix() {
        let src = init_source("std");
        for e in entries() {
            assert!(
                src.contains(&format!("require(\"std.{}\")", e.name)),
                "{src}"
            );
            assert!(src.contains(&format!("   {}: ", e.name)), "{src}");
        }
        assert!(src.contains("local record std\n"));
        assert!(src.ends_with("return std\n"));
    }

    #[test]
    fn write_to_nests_a_dotted_prefix() {
        let dir = std::env::temp_dir().join(format!(
            "mlua-batteries-dts-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        let written = write_to(&dir, "vendor.std").unwrap();
        assert!(written
            .iter()
            .all(|p| p.starts_with(dir.join("vendor").join("std"))));
        assert!(dir.join("vendor/std/init.d.tl").is_file());
        assert_eq!(written.len(), entries().len() + 1);
        fs::remove_dir_all(&dir).unwrap();
    }
}
